--- #YAML:1.0
name:                Statistics-RankCorrelation
version:             0.11_3
abstract:            Compute the rank correlation between two vectors 
license:             ~
author:              
    - Gene Boggs <gene@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
